name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev python3-dev
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r reqs.txt
    
    - name: Create vosk model directory
      run: |
        mkdir -p vosk
        echo "Mock directory for vosk models" > vosk/README.md
    
    - name: Run tests with coverage
      run: |
        pytest --cov=lib --cov-report=xml --cov-report=term tests/ -v
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_ORG: ${{ secrets.OPENAI_ORG }}
        OPENAI_PROJ: ${{ secrets.OPENAI_PROJ }}
        OLLAMA_API_URL: http://localhost:11434/api/generate
        OLLAMA_MODEL: mock-model
        PYTHONPATH: ${{ github.workspace }}